AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Conversational RAG chain

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: python3.9
      CodeUri: .
      MemorySize: 512
      Timeout: 15
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
